/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.Controller;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import patientmanagementsystem.Appointment;
import patientmanagementsystem.Doctor;
import patientmanagementsystem.Patient;

/**
 *
 * @author ahoughton-vowles
 */
public class PatientForm extends javax.swing.JFrame {

    Controller controller = new Controller();
    ArrayList<String> notifications;
    Appointment currentAppointment;
    
    /**
     * Creates new form PatientForm
     */
    public PatientForm() {
        initComponents();
        getNotifications();
        GetDoctors();
        SetupAppointments();
        SelectAppointment();
    }

    private void SetupAppointments()
    {
        ArrayList<Appointment> a = controller.GetAppointments((Patient)controller.getCurrentUser());
        DefaultComboBoxModel model = new DefaultComboBoxModel();        
        for (int i = 0; i < a.size(); i++) {
            model.addElement(a.get(i).getTime());
        }
        cmb_Appointments.setModel(model);
        
        
    }
    
    private void SelectAppointment()
    {
        
        ArrayList<Appointment> a = controller.GetAppointments((Patient)controller.getCurrentUser());
        
        if (a.size() > 0) {
            currentAppointment = a.get(cmb_Appointments.getSelectedIndex());
            controller.SetCurrentAppointment(currentAppointment);
            String name = a.get(cmb_Appointments.getSelectedIndex()).getDoctor().getGivenName() + " " + a.get(cmb_Appointments.getSelectedIndex()).getDoctor().getSurName();
            lblDoctor.setText(name);
        
            currentAppointment = a.get(cmb_Appointments.getSelectedIndex());
            txt_Notes.setText(currentAppointment.getNotes());
        }
        
    }
    
    private void GetDoctors()
    {
        ArrayList<String> names = controller.GetDoctorNames();
        DefaultComboBoxModel model = new DefaultComboBoxModel();        
        for (int i = 0; i < names.size(); i++) {
            model.addElement(names.get(i));
        }
        cmb_Doctor.setModel(model);
    }
    
    private void getNotifications()
    {
        notifications = controller.getNotifications(controller.getCurrentUser().getId());
        DefaultListModel model = new DefaultListModel();        
        for (int i = 0; i < notifications.size(); i++) {
            model.addElement(notifications.get(i));
        }
        lst_noti.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lst_Noti = new javax.swing.JScrollPane();
        lst_noti = new javax.swing.JList<>();
        btn_LogOut = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Reviews = new javax.swing.JButton();
        btn_RequestAppointment = new javax.swing.JButton();
        cmb_Doctor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txt_Time = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmb_Appointments = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Notes = new javax.swing.JTextArea();
        btn_Prescribe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lst_Noti.setViewportView(lst_noti);

        btn_LogOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_LogOut.setText("Log Out");
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });

        btn_Delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_Delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Delete.setText("Request Account Deletion");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Reviews.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Reviews.setText("Doctor Reviews");
        btn_Reviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReviewsActionPerformed(evt);
            }
        });

        btn_RequestAppointment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_RequestAppointment.setText("RequestAppointment");
        btn_RequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RequestAppointmentActionPerformed(evt);
            }
        });

        jLabel1.setText("Doctor");

        jLabel2.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Reviews)
                    .addComponent(btn_LogOut)
                    .addComponent(btn_Delete)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_RequestAppointment)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_Doctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Time)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel2)))
                                .addGap(0, 110, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lst_Noti, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lst_Noti, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7)
                                .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_RequestAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Reviews)
                        .addGap(18, 18, 18)
                        .addComponent(btn_LogOut)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Delete)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Patient View", jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select Appointment:");

        cmb_Appointments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_Appointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_AppointmentsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Doctor:");

        lblDoctor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDoctor.setText("---");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Notes:");

        txt_Notes.setEditable(false);
        txt_Notes.setColumns(20);
        txt_Notes.setRows(5);
        jScrollPane1.setViewportView(txt_Notes);

        btn_Prescribe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Prescribe.setText("View Prescription");
        btn_Prescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrescribeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmb_Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel5)
                            .addComponent(btn_Prescribe))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDoctor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Prescribe)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Appointment View", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        // TODO add your handling code here:
        controller.LogOut();
        this.setVisible(false);
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        controller.RequestTermination();
        getNotifications();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_ReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReviewsActionPerformed
        // TODO add your handling code here:
        DoctorRatings form = new DoctorRatings();
        form.setVisible(true);
    }//GEN-LAST:event_btn_ReviewsActionPerformed

    private void btn_RequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RequestAppointmentActionPerformed
        // TODO add your handling code here:
        controller.RequestAppointment(cmb_Doctor.getModel().getSelectedItem().toString(), txt_Time.getText());
    }//GEN-LAST:event_btn_RequestAppointmentActionPerformed

    private void cmb_AppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_AppointmentsActionPerformed
        // TODO add your handling code here:
        SelectAppointment();
    }//GEN-LAST:event_cmb_AppointmentsActionPerformed

    private void btn_PrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrescribeActionPerformed
        // TODO add your handling code here:
        PrescriptionView form = new PrescriptionView();
        form.setVisible(true);
        
    }//GEN-LAST:event_btn_PrescribeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_Prescribe;
    private javax.swing.JButton btn_RequestAppointment;
    private javax.swing.JButton btn_Reviews;
    private javax.swing.JComboBox<String> cmb_Appointments;
    private javax.swing.JComboBox<String> cmb_Doctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JScrollPane lst_Noti;
    private javax.swing.JList<String> lst_noti;
    private javax.swing.JTextArea txt_Notes;
    private javax.swing.JTextField txt_Time;
    // End of variables declaration//GEN-END:variables
}
